title: AstroCan17
description: Satellite Ground Segment Architect — Payload Data Processing — Cal/Val & EO ML
baseurl: "/AstroCan17"
url: "https://astrocan17.github.io"
markdown: kramdown
kramdown:
  input: GFM
